// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SegParcial.DAL;

namespace SegParcial.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("SegParcial.Entidades.Llamadas", b =>
                {
                    b.Property<int>("Llamadaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.HasKey("Llamadaid");

                    b.ToTable("Llamadas");
                });

            modelBuilder.Entity("SegParcial.Entidades.LlamadasDetalles", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Llamadaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Problema")
                        .HasColumnType("TEXT");

                    b.Property<string>("Solucion")
                        .HasColumnType("TEXT");

                    b.HasKey("IdDetalle");

                    b.HasIndex("Llamadaid");

                    b.ToTable("LlamadasDetalles");
                });

            modelBuilder.Entity("SegParcial.Entidades.LlamadasDetalles", b =>
                {
                    b.HasOne("SegParcial.Entidades.Llamadas", null)
                        .WithMany("Telefono")
                        .HasForeignKey("Llamadaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
